version: "2"
services:
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/plex:/config
      - /storage/tvseries:/tv
      - /storage/movies:/movies
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/sonarr/config
      - /storage/tvseries:/tv
      - /storage/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/radarr:/config
      - /storage/movies:/movies
      - /storage/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/jackett:/config
      - /storage:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    extends:
      file: base.yml
      service: base
    volumes:
      ~/config/deluge:/config
      - /storage/downloads:/downloads
      - ~/config/bazarr:/config
      - /storage/movies:/movies
      - /storage/tvseries:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    extends:
      file: base.yml
      service: base
    environment:
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ~/config/calibre-web:/config
      - /storage/calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/tautulli:/config
      - ~/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    extends:
      file: base.yml
      service: base
    environment:
      - WEBUI_PORT=5000
    volumes:
      - ~/config/qbittorrent:/config
      - /storage/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 5000:5000
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/prometheus/:/etc/prometheus/
      - ~/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    extends:
      file: base.yml
      service: base
    depends_on:
      - prometheus
    ports:
      - 3001:3000
    volumes:
      - ~/data/prometheus:/var/lib/grafana
      - ~/config/prometheus:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    user: "104"
