version: "2.3"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    runtime: nvidia
    extends:
      file: base.yml
      service: base
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/config/plex:/config
      - /storage/tv:/tv
      - /storage/movies:/movies
    restart: unless-stopped

  sonarr-beta:
    image: hotio/sonarr
    container_name: sonarr-beta
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/sonarr-beta:/config
      - /storage/tv:/tv
      - /storage/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/radarr:/config
      - /storage/movies:/movies
      - /storage/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/jackett:/config
      - /storage:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/bazarr:/config
      - /storage/movies:/movies
      - /storage/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    extends:
      file: base.yml
      service: base
    environment:
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ~/config/calibre-web:/config
      - /storage/calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    extends:
      file: base.yml
      service: base
    volumes:
      - ~/config/tautulli:/config
      - ~/config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped

  surfshark-0:
    image: ilteoood/docker-surfshark
    container_name: surfshark-0
    environment: 
      - SURFSHARK_USER=
      - SURFSHARK_PASSWORD=
      - SURFSHARK_COUNTRY=se
      - SURFSHARK_CITY=sto
      - CONNECTION_TYPE=udp
      - LAN_NETWORK=10.0.0.0/24
    cap_add: 
      - NET_ADMIN
    devices:
       - /dev/net/tun
    ports:
      - 5000:5000
    restart: unless-stopped
    dns:
      - 1.1.1.1
# :14.2.4.99202004222217-7004-50f676cubuntu18.04.1-ls75
  qbittorrent-0:
    image: linuxserver/qbittorrent
    container_name: qbittorrent-0
    depends_on: 
      - surfshark-0
    extends:
      file: base.yml
      service: base
    environment:
      - WEBUI_PORT=5000
    volumes:
      - ~/config/qbittorrent-0:/config
      - /storage/downloads:/downloads
    # ports:
      # - 6881:6881
      # - 6881:6881/udp
      # - 5000:5000
    network_mode: service:surfshark-0
    restart: unless-stopped

  surfshark-1:
    image: ilteoood/docker-surfshark
    container_name: surfshark-1
    environment: 
      - SURFSHARK_USER=
      - SURFSHARK_PASSWORD=
      - SURFSHARK_COUNTRY=nl
      - SURFSHARK_CITY=ams
      - CONNECTION_TYPE=udp
      - LAN_NETWORK=10.0.0.0/24
    cap_add: 
      - NET_ADMIN
    devices:
       - /dev/net/tun
    ports:
      - 5001:5001
    restart: unless-stopped
    dns:
      - 1.1.1.1

  qbittorrent-1:
    image: linuxserver/qbittorrent
    container_name: qbittorrent-1
    depends_on: 
      - surfshark-1
    extends:
      file: base.yml
      service: base
    environment:
      - WEBUI_PORT=5001
    volumes:
      - ~/config/qbittorrent-1:/config
      - /storage/downloads:/downloads
    # ports:
      # - 6881:6881
      # - 6881:6881/udp
      # - 5001:5000
    network_mode: service:surfshark-1
    restart: unless-stopped

  # axigen:
  #   container_name: axigen
  #   image: axigen/axigen
  #   ports:
  #     # - "21:21"
  #     # - "25:25"
  #     # - "80:80"
  #     # - "110:110"
  #     # - "143:143"
  #     - "443:443"
  #     - "465:465"
  #     - "993:993"
  #     - "995:995"        
  #     # - "9000:9000"
  #     - "9443:9443"
  #     # - "7000:7000"
  #   volumes:
  #     - './config/axigen/:/var/opt/axigen/'
  #   restart: unless-stopped

  node-exporter:
    privileged: true
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
  
  dcgm-exporter:
    container_name: dcgm-exporter
    runtime: nvidia
    image: nvcr.io/nvidia/k8s/dcgm-exporter
    ports:
      - 9400:9400
    restart: always
