version: "3"
services:
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - UMASK_SET=022 
    volumes:
      - ./config/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
